{% set name = "autoconf-archive" %}
{% set version = "2018.03.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/autoconf-archive/{{ name }}-{{ version }}.tar.xz
  sha256: 6175f90d9fa64c4d939bdbb3e8511ae0ee2134863a2c7bf8d9733819efa6e159

build:
{% if bootstrapping == 'yes' %}
  # Please increment by two
  number: 0
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_bootstrapping
{% else %}
  # Keep above the number of the _bootstrapping package
  number: 1
{% endif %}
  skip: True  # [win]
  script_env:
    - BOOTSTRAPPING={{ bootstrapping }}

requirements:
{% if bootstrapping != 'yes' %}
  build:
    - autoconf
  run:
    - autoconf
{% endif %}

test:
  commands:
    - test -d ${PREFIX}/share/autoconf-archive

about:
  home: https://savannah.gnu.org/projects/autoconf-archive/
  license: GPL-3.0
  license_family: GPL
  summary: Collection of over 500 reusable autoconf macros

extra:
  recipe-maintainers:
    - egpbos
    - mcs07
